# Generated by Django 3.1 on 2023-01-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='monthlyCount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
