# Generated by Django 3.1 on 2023-11-12 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blogIdea',
            new_name='blog_idea',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='lastUpdated',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='wordCount',
            new_name='word_count',
        ),
        migrations.RenameField(
            model_name='blogsection',
            old_name='dateCreated',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='blogsection',
            old_name='lastUpdated',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='blogsection',
            old_name='wordCount',
            new_name='word_count',
        ),
    ]
