# Generated by Django 3.1 on 2023-01-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230102_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsection',
            name='word_count',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
